export enum LanguageZone {
    Default = "default",
    Arabic = "ar_ae",
    Czech = "cs_cz",
    German = "de_de",
    Greek = "el_gr",
    EnglishAustralia = "en_au",
    EnglishGreatBritain = "en_gb",
    EnglishPhilippines = "en_ph",
    EnglishSingapore = "en_sg",
    SpanishArgentina = "es_ar",
    SpanishSpain = "es_es",
    SpanishMexico = "es_mx",
    FrenchFrance = "fr_fr",
    Hungarian = "hu_hu",
    Italian = "it_it",
    Japanese = "ja_jp",
    Korean = "ko_kr",
    Polish = "pl_pl",
    PortugueseBrazil = "pt_br",
    Romanian = "ro_ro",
    Russian = "ru_ru",
    Thai = "th_th",
    Turkish = "tr_tr",
    Vietnamese = "vi_vn",
    ChineseChina = "zh_cn",
    ChineseMalaysia = "zh_my",
    ChineseTaiwan = "zh_tw",
}

export type LangAssets<T> = Partial<Record<LanguageZone, T>>;